### PR TITLE
Initial FamilyMemberHistory example

### PR DESCRIPTION
**Pull request by APageNHS**
FMH profile was lacking an example, this gives one for a father, with diabetes

### CODE REVIEW

**Review by omarisgreat — APPROVED** [review]
Looks good to me

**Review by ryma2fhir — COMMENTED** [review]
Not sure the identifier is correct. The Design&development approach had it as 

><identifier>
>   <system value="urn:ietf:rfc:3986"/>
>    <value value="urn:oid:[object identifier]"/>
></identifier>

https://simplifier.net/guide/HL7FHIRUKCoreDesignandDevelopmentApproach/Home/Asset-Design/ValueSet-Design?version=current

**Comment by declankieran-nhsd** [comment]
It doesn't seem to be an oid, so if its just a uuid, a "urn:uuid:" prefix is probably more correct. But if it is just a uuid, what does it add beyond using a uuid for the id?  Why is it needed for a business identifier?

**Comment by APageNHS** [comment]
> It doesn't seem to be an oid, so if its just a uuid, a "urn:uuid:" prefix is probably more correct. But if it is just a uuid, what does it add beyond using a uuid for the id? Why is it needed for a business identifier?

I came to same conclusion, identifer inclusion isn't mandatory and using a uuid wasn't giving any value, so removed

**Review by ryma2fhir — APPROVED** [review]

**Review by declankieran-nhsd — APPROVED** [review]

**Pull request merged**
