### PR TITLE
Fix/ballot 1.0.0 issue 15

### PR DESCRIPTION
**Pull request by declankieran-nhsd**
@unicorn150161 , @johngeo for review please.

Update Extension names and references as per ballot item # 15.  

The following references in the IG will need updated.

```shellscript
Home/ProfilesandExtensions/ExtensionLibrary/Index.page.md:179:<td><h5>{{pagelink:ExtensionUKCore-MedicationPrescribingOrganization}}</h5></td>

Home/ProfilesandExtensions/ExtensionLibrary/ExtensionUKCore-MedicationPrescribingOrganization.page.md:1:## StructureDefinition Extension-UKCore-MedicationPrescribingOrganization
Home/ProfilesandExtensions/ExtensionLibrary/ExtensionUKCore-MedicationPrescribingOrganization.page.md:33:{{tree:https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-MedicationPrescribingOrganization, snapshot}}
Home/ProfilesandExtensions/ExtensionLibrary/ExtensionUKCore-MedicationPrescribingOrganization.page.md:38:{{tree:https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-MedicationPrescribingOrganization, diff}}
Home/ProfilesandExtensions/ExtensionLibrary/ExtensionUKCore-MedicationPrescribingOrganization.page.md:43:{{tree:https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-MedicationPrescribingOrganization, hybrid}}
Home/ProfilesandExtensions/ExtensionLibrary/ExtensionUKCore-MedicationPrescribingOrganization.page.md:48:{{table:https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-MedicationPrescribingOrganization, snapshot}}
Home/ProfilesandExtensions/ExtensionLibrary/ExtensionUKCore-MedicationPrescribingOrganization.page.md:52:{{xml:https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-MedicationPrescribingOrganization, snapshot}}
Home/ProfilesandExtensions/ExtensionLibrary/ExtensionUKCore-MedicationPrescribingOrganization.page.md:56:{{json:https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-MedicationPrescribingOrganization, snapshot}}

Home/ProfilesandExtensions/ProfileUKCore-MedicationStatement/extensionmedicationPrescribingOrganization.page.md:9:{{pagelink:ExtensionUKCore-MedicationPrescribingOrganization}}.

Home/Terminology/ValueSetsandCodeSystems.page.md:266:<a href="https://simplifier.net/guide/HL7FHIRUKCoreR4Release1/Home/ProfilesandExtensions/ExtensionLibrary/ExtensionUKCore-MedicationPrescribingOrganization.guide.md">ExtensionUKCore-MedicationPrescribingOrganization</a><br/>
```

CC: @SheenaSharma , @ryma2fhir , @KazeemHamzat

### CODE REVIEW

**Review by johngeo — CHANGES_REQUESTED** [review]
Hi Declan, when I opened the profile UKCore-MedicationStatement in Forge, it displays the extension as extension:medicationPrescribingOrganization.  I'll email you a screenshot.

**Review by johngeo — CHANGES_REQUESTED** [review]
Hi Declan, I can see that you've made the changes to the MedicationStatement profile, that looks good.  However, I had a look at Extension-UKCore-MedicationPrescribingOrganizationType in Forge.  It showing it is bound to ...ValueSet/UKCore-MedicationPrescribingOrganization.  Shouldn't this be bound to ...ValueSet/UKCore-MedicationPrescribingOrganizationType?  I'll email you a screenshot.

**Comment by declankieran-nhsd** [comment]
@johngeo The ValueSet changes were did in #40, I've only did the extension changes in this repo.  I thought history wise that it would be better for referencing back when looking at individual issues, although in hindsight it would maybe have been better if the issues were all amalgamated per section or related change...  

If you have a look at the merge conflicts they are related to these values, so once these are resolved it should be correct (which I'll do when I merge into develop).

image

**Comment by johngeo** [comment]
@declankieran-nhsd thanks, that explains the merge conflicts.

**Review by johngeo — APPROVED** [review]
Changes look fine.

**Pull request merged**
