### PR TITLE
remove concept details from example

### PR DESCRIPTION
**Pull request by APageNHS**
Example is meant to be used in the Sending a concept where the coding system and code is unknown example, but contained a code...

https://nhsd-jira.digital.nhs.uk/browse/IOPS-928

### CODE REVIEW

**Comment by declankieran-nhsd** [comment]
I think the CodeUnknown in the name was useful given how little is in the snippet, adding the myocardial infarction bit in was a good idea though, a formal naming convention for these would be useful

**Comment by APageNHS** [comment]
> I think the CodeUnknown in the name was useful given how little is in the snippet, adding the myocardial infarction bit in was a good idea though, a formal naming convention for these would be useful

Are we thinking UKCore-Condition-Sn-Extension-CodingSCT-CodeUnknown-MyocardialInfarction-Example would be better, as its fully descriptive of what the example is

**Comment by declankieran-nhsd** [comment]
> > I think the CodeUnknown in the name was useful given how little is in the snippet, adding the myocardial infarction bit in was a good idea though, a formal naming convention for these would be useful
> 
> Are we thinking UKCore-Condition-Sn-Extension-CodingSCT-CodeUnknown-MyocardialInfarction-Example would be better, as its fully descriptive of what the example is

I'm a fan of fully descriptive names as I don't think the length is generally a problem, certainly with a filename on a modern OS (I think windows can still be a bit restrictive on file path names).  I think the CodeUnknown part is useful here given the lack of content in the snippet.  Another option could be to add a comment in the snippet to maybe refer to the guidance, but I'd be wary of doing that as it might end up just repeating the same thing and it would end up out of sync, plus this example is included in the IG in table format.  So in short, yeah I think ` UKCore-Condition-Sn-Extension-CodingSCT-CodeUnknown-MyocardialInfarction-Example` seems the best option...

**Comment by declankieran-nhsd** [comment]
Sorry, actually I thin removing the Myocardial part is probably better and more concise, I was thinking you'd changed it the other way round

**Comment by declankieran-nhsd** [comment]
I just fixed the indent there, going to go ahead and approve if you're happy

**Review by declankieran-nhsd — APPROVED** [review]

**Pull request merged**
