### PR TITLE
Feature/adding new profile 2 uk core family member history

### PR DESCRIPTION
**Pull request by KazeemHamzat**
Here is a draft of both FHM and Subscription.
There is a need to standardise the content for description and purpose on the 2 profiles.

### CODE REVIEW

**Comment by KevinMayfield** [comment]
Both profiles need the snapshot removed before approval.

**Review by KevinMayfield — CHANGES_REQUESTED** [review]
snapshot needs removing

**Comment by omarisgreat** [comment]
Hi Both, The guidance document (for developing profiles for UK Core) we got from John stated the 'snapshot component' must be included. I'll take this up with him as it looks like the guidance is incorrect

**Comment by johngeo** [comment]
Hi @omarisgreat,sorry the guidance was was out of date, I've updated the guidance for UKCore-InitialProfilingApproach.docx see: https://hscic365.sharepoint.com/:w:/r/sites/FHIRUKCore/Shared%20Documents/General/UKCore-InitialProfilingApproach.docx?d=w4eea683a9d614df58284cb7e06c43df3&csf=1&web=1&e=ysGDhn

**Comment by KevinMayfield** [comment]
FYI The quality of the snapshot from Forge isn't that great and also fire.ly recommended not including one. 

I've also added a check in the github test scripts to check for absence of snapshots and will raise an error if it finds one.

**Pull request closed without merging**
