### PR TITLE
set messageevent binding to example

### PR DESCRIPTION
**Pull request by APageNHS**
as per standup call discussion, set binding to MessageEvent valueset which uses NHSD codesystems to 'example'

### CODE REVIEW

**Review by declankieran-nhsd — APPROVED** [review]
No issue with this, however looking at the code systems in

`https://fhir.hl7.org.uk/ValueSet/UKCore-MessageEvent`

one is pointing to `https://fhir.nhs.uk/CodeSystem/message-event`, would have thought it should have been `https://fhir.hl7.org.uk/CodeSystem/UKCore-MessageEvent`

The other one is a BARS one `https://fhir.nhs.uk/CodeSystem/message-events-bars` which is maybe fine, although the NHSD fhir reference server at https://fhir.nhs.uk/CodeSystem/ doesn't seem to have those available, although lots of things are missing there...

**Comment by APageNHS** [comment]
> https://fhir.hl7.org.uk/CodeSystem/UKCore-MessageEvent



> one is pointing to `https://fhir.nhs.uk/CodeSystem/message-event`, would have thought it should have been `https://fhir.hl7.org.uk/CodeSystem/UKCore-MessageEvent`

that https://fhir.hl7.org.uk/CodeSystem/UKCore-MessageEvent is blank, and was causing a problem, which was why we changed the valueset to have the NHSD ones, and now as discussed we've decided to make this example rather than preferred

**Comment by declankieran-nhsd** [comment]
Ah ok, sorry mustn't have caught that on the call.  When not just revert back to the base example then, what's the purpose of providing an empty example?  I think I'd find this very confusing, even if it will be bound to a valueset eventually, this provides nothing to the end user of the profile.

**Comment by declankieran-nhsd** [comment]
Or is there codes in the NHSD ones, in which case that's fine, just wasn't handy getting it at the canonical and didn't bother going hunting for them in the repos

**Comment by APageNHS** [comment]
> Or is there codes in the NHSD ones, in which case that's fine, just wasn't handy getting it at the canonical and didn't bother going hunting for them in the repos

KevinM provided the NHSD urls, according to github, the BARS one is populated: https://github.com/NHSDigital/NHSDigital-FHIR-ImplementationGuide/blob/master/CodeSystem/BARS-message-events.json

**Pull request merged**
