### PR TITLE
Fix/ballot 1.0.0 issue 22

### PR DESCRIPTION
**Pull request by ryma2fhir**
Changed 'should' to 'Should', 'MUST' to 'SHALL'

### CODE REVIEW

**Review by declankieran-nhsd — COMMENTED** [review]
Are you looking to change all instances of must (lower and upper case) to SHALL, as well as capitalising all instances of should (where should is indicating a requirement)?

A quick grep (`grep -rinw -E "must|should" .`) at the root of the repo returned some that aren't included here

```
./codesystems/CodeSystem-NHSDataModelAndDictionary-SourceOfAdmission.xml:51:    <definition value="National Code 51 'NHS other hospital provider - Ward for general Patients or the younger physically disabled or A and E department' should not be used if the Patient arrives at an Accident and Emergency Department and is admitted to the same Hospital Provider." />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:40:            <definition value="The System must create a new prescription UUID and re-submit the prescription to the Spine." />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:45:            <definition value="The System must create and apply a digital signature to the prescription and re-submit the prescription to the Spine" />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:50:            <definition value="The prescription message has failed structural validation at the Spine. A defect report should be raised against the local System or the Spine (whichever is in error). The prescriber must be notified accordingly to use a paper FP10 prescription." />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:54:            <display value="Number of items on a prescription should be between 1 and 4" />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:55:            <definition value="The prescriber must be notified accordingly and asked to split the items across separate prescriptions." />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:64:            <display value="Repeat count should be between 1 and 99" />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:70:            <definition value="The System must create a new line item UUID and re-submit the prescription to the Spine." />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:75:            <definition value="The System must re-calculate / correct the check digit and re-submit the prescription to the Spine." />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:80:            <definition value="The format of a date/time attribute with the prescription does not confirm with the format defined within the DMS. The System must correct the date/time attribute and re-submit the prescription to the Spine." />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:105:           <definition value="No further request messages to pull down nominated prescriptions should be submitted at this time" />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:110:           <definition value="The Spine nomination functionality has been disabled at the request of the Authority and the message is rejected. The request will not be processed. However, the prescription request by prescription unique identifier should be available." />
./codesystems/CodeSystem-UKCore-SpineErrorOrWarningCode.xml:75:         <definition value="Too many matches were found - user should refine their search parameters." />
./codesystems/CodeSystem-UKCore-SpineErrorOrWarningCode.xml:140:                <definition value="When polling an ID, a message was found to be in a failed state, so there is nothing else to be done and should be considered a failure." />
./examples/UKCore-Schedule-Immunization-Example.xml:41: <comment value="The slots attached to this schedule should be specialized to cover immunizations within
./examples/UKCore-Slot-AvailableWalkInVisit-Example.xml:47:     <comment value="Assessments should be performed before requesting appointments in this slot."/>
./structuredefinitions/Extension-UKCore-CopyCorrespondenceIndicator.xml:29:  <description value="Indicates that a Patient contact or RelatedPerson must be copied in to Patient correspondence." />
./structuredefinitions/Extension-UKCore-CopyCorrespondenceIndicator.xml:30:  <purpose value="This extension extends the Patient and RelatedPerson resources, to support the exchange of information to indicate that a Patient contact or RelatedPerson must be copied in to Patient correspondence. This is currently not supported by the FHIR standard." />
./structuredefinitions/Extension-UKCore-CopyCorrespondenceIndicator.xml:54:      <short value="Indicator showing that a patient's contact or related person must be copied in to patient correspondence" />
./structuredefinitions/Extension-UKCore-CopyCorrespondenceIndicator.xml:55:      <definition value="Extension carrying a boolean indicator showing that a patient's contact or related person must be copied in to patient correspondence." />
./structuredefinitions/UKCore-Composition.xml:30:  <purpose value="This profile allows a record of a set of healthcare-related information that is assembled together into a single logical package that provides a single coherent statement of meaning, establishes its own context and that has clinical attestation with regard to who is making the statement. A Composition defines the structure and narrative content necessary for a document. However, a Composition alone does not constitute a document. Rather, the Composition must be the first entry in a Bundle where Bundle.type=document, and any other resources referenced from Composition must be included as subsequent entries in the Bundle, for example Patient, Practitioner, Encounter, etc." />
./structuredefinitions/UKCore-Composition.xml:66:      <definition value="A set of healthcare-related information that is assembled together into a single logical package that provides a single coherent statement of meaning, establishes its own context and that has clinical attestation with regard to who is making the statement. A Composition defines the structure and narrative content necessary for a document. However, a Composition alone does not constitute a document. Rather, the Composition must be the first entry in a Bundle where Bundle.type=document, and any other resources referenced from Composition must be included as subsequent entries in the Bundle, for example Patient, Practitioner, Encounter, etc." />
./structuredefinitions/UKCore-Consent.xml:30:  <purpose value="The purpose of this profile is to be used to express a Consent regarding Healthcare. There are four anticipated uses for the Consent Resource, all of which are written or verbal agreements by a healthcare consumer [grantor] or a personal representative, made to an authorised entity [grantee] concerning authorised or restricted actions with any limitations on purpose of use, and handling instructions to which the authorised entity must comply:&#xD;&#xA; · Privacy Consent Directive: Agreement to collect, access, use or disclose (share) information.&#xD;&#xA; · Medical Treatment Consent Directive: Consent to undergo a specific treatment (or record of refusal to consent).&#xD;&#xA; · Research Consent Directive: Consent to participate in research protocol and information sharing required.&#xD;&#xA; · Advance Care Directives: Consent to instructions for potentially needed medical treatment (e.g. DNR)." />
./structuredefinitions/UKCore-Immunization.xml:69:        <human value="If the immunization was not given then Immunization.status value MUST = 'not-done', and the Immunization.statusReason MUST be populated" />
./structuredefinitions/UKCore-Observation.xml:30:  <purpose value="This profile allows exchange of information of Measurements and simple assertions made about an individual, device or other subject. Note: this profile MUST not be used where a more specific UK Core profile exists." />
./structuredefinitions/UKCore-Organization.xml:82:      <short value="The date range that this organization should be considered available." />
./structuredefinitions/UKCore-Organization.xml:83:      <definition value="The date range that this organization should be considered available." />
./structuredefinitions/UKCore-Organization.xml:93:      <short value="The date range that this organization should be considered available." />
./structuredefinitions/UKCore-Organization.xml:94:      <definition value="The date range that this organization should be considered available." />
./structuredefinitions/UKCore-Task.xml:30:  <purpose value="A task resource describes an activity that can be performed and tracks the state of completion of that activity. It is a representation that an activity should be or has been initiated, and eventually, represents the successful or unsuccessful completion of that activity.&#xD;&#xA;&#xD;&#xA;Note that there are a variety of processes associated with making and processing orders. Some orders may be handled immediately by automated systems but most require real world actions by one or more humans. Some orders can only be processed when other real world actions happen, such as a patient presenting themselves so that the action to be performed can actually be performed. Often these real world dependencies are only implicit in the order details." />
./valuesets/ValueSet-UKCore-OperationOutcomeIssueDetails.xml:280:                       <display value="Number of items on a prescription should be between 1 and 4"/>
./valuesets/ValueSet-UKCore-OperationOutcomeIssueDetails.xml:382:                       <display value="Repeat count should be between 1 and 99"/>
./valuesets/ValueSet-UKCore-SpecimenType.xml:36:                                <value value="(&lt;105590001 |Substance (in which case method and site should also be populated)|OR &lt;49755003 |Morphologically abnormal structure|OR &lt; 260787004 |Physical object|)"/>
./valuesets/ValueSet-UKCore-SubstanceOrProductAdministrationRoute.xml:30:&#13; - with which a medication was or should be administered to a patient;
```

**Comment by ryma2fhir** [comment]
Thanks @declankieran-nhsd. I am wanting to change any which denote the FHIR conformance language (SHALL, SHOULD, MAY), unfortunately there many instances in which 'shall, should, may' have been used which are not intended to be requirements under FHIR and is being used as general language. 

I've picked the ones that I'm certain are, the others don't seem to be but if you wouldn't mind having a look through and seeing if I've missed any

**Comment by declankieran-nhsd** [comment]
The in `./codesystems/CodeSystem-UKCore-EPSIssueCode.xml`

./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:40:            <definition value="The System **must** create a new prescription UUID and re-submit the prescription to the Spine." />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:45:            <definition value="The System **must** create and apply a digital signature to the prescription and re-submit the prescription to the Spine" />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:50:            <definition value="The prescription message has failed structural validation at the Spine. A defect report **should** be raised against the local System or the Spine (whichever is in error). The prescriber **must** be notified accordingly to use a paper FP10 prescription." />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:55:            <definition value="The prescriber **must** be notified accordingly and asked to split the items across separate prescriptions." />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:70:            <definition value="The System **must** create a new line item UUID and re-submit the prescription to the Spine." />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:75:            <definition value="The System **must** re-calculate / correct the check digit and re-submit the prescription to the Spine." />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:80:            <definition value="The format of a date/time attribute with the prescription does not confirm with the format defined within the DMS. The System **must** correct the date/time attribute and re-submit the prescription to the Spine." />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:110:           <definition value="The Spine nomination functionality has been disabled at the request of the Authority and the message is rejected. The request will not be processed. However, the prescription request by prescription unique identifier **should** be available." />

These below actually look as if they MUST (or SHALL given FHIR guidance) should be used instead of should, given it is a definitive range, for example it doesn't seem valid that I might use a repeat count of 100 given the definition says "The maximum “high” value for the “repeatNumber” attribute is 99."  Maybe 0 is valid, but probably something that would be included depending on cardinality of the particular element.

./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:54:            <display value="Number of items on a prescription **should** be between 1 and 4" />
./codesystems/CodeSystem-UKCore-EPSIssueCode.xml:64:            <display value="Repeat count **should** be between 1 and 99" />

These in `./structuredefinitions/Extension-UKCore-CopyCorrespondenceIndicator.xml`

./structuredefinitions/Extension-UKCore-CopyCorrespondenceIndicator.xml:29:  <description value="Indicates that a Patient contact or RelatedPerson **must** be copied in to Patient correspondence." />
./structuredefinitions/Extension-UKCore-CopyCorrespondenceIndicator.xml:30:  <purpose value="This extension extends the Patient and RelatedPerson resources, to support the exchange of information to indicate that a Patient contact or RelatedPerson **must** be copied in to Patient correspondence. This is currently not supported by the FHIR standard." />
./structuredefinitions/Extension-UKCore-CopyCorrespondenceIndicator.xml:54:      <short value="Indicator showing that a patient's contact or related person **must** be copied in to patient correspondence" />
./structuredefinitions/Extension-UKCore-CopyCorrespondenceIndicator.xml:55:      <definition value="Extension carrying a boolean indicator showing that a patient's contact or related person **must** be copied in to patient correspondence." />

These in `./structuredefinitions/UKCore-Composition.xml`

./structuredefinitions/UKCore-Composition.xml:30:  <purpose value="This profile allows a record of a set of healthcare-related information that is assembled together into a single logical package that provides a single coherent statement of meaning, establishes its own context and that has clinical attestation with regard to who is making the statement. A Composition defines the structure and narrative content necessary for a document. However, a Composition alone does not constitute a document. Rather, the Composition **must** be the first entry in a Bundle where Bundle.type=document, and any other resources referenced from Composition **must** be included as subsequent entries in the Bundle, for example Patient, Practitioner, Encounter, etc." />
./structuredefinitions/UKCore-Composition.xml:66:      <definition value="A set of healthcare-related information that is assembled together into a single logical package that provides a single coherent statement of meaning, establishes its own context and that has clinical attestation with regard to who is making the statement. A Composition defines the structure and narrative content necessary for a document. However, a Composition alone does not constitute a document. Rather, the Composition **must** be the first entry in a Bundle where Bundle.type=document, and any other resources referenced from Composition **must** be included as subsequent entries in the Bundle, for example Patient, Practitioner, Encounter, etc." />

In `./structuredefinitions/UKCore-Consent.xml`

./structuredefinitions/UKCore-Consent.xml:30:  <purpose value="The purpose of this profile is to be used to express a Consent regarding Healthcare. There are four anticipated uses for the Consent Resource, all of which are written or verbal agreements by a healthcare consumer [grantor] or a personal representative, made to an authorised entity [grantee] concerning authorised or restricted actions with any limitations on purpose of use, and handling instructions to which the authorised entity **must** comply:&#xD;&#xA; · Privacy Consent Directive: Agreement to collect, access, use or disclose (share) information.&#xD;&#xA; · Medical Treatment Consent Directive: Consent to undergo a specific treatment (or record of refusal to consent).&#xD;&#xA; · Research Consent Directive: Consent to participate in research protocol and information sharing required.&#xD;&#xA; · Advance Care Directives: Consent to instructions for potentially needed medical treatment (e.g. DNR)." />

These in `./structuredefinitions/UKCore-Organization.xml`

./structuredefinitions/UKCore-Organization.xml:82:      <short value="The date range that this organization **should** be considered available." />
./structuredefinitions/UKCore-Organization.xml:83:      <definition value="The date range that this organization **should** be considered available." />
./structuredefinitions/UKCore-Organization.xml:93:      <short value="The date range that this organization **should** be considered available." />
./structuredefinitions/UKCore-Organization.xml:94:      <definition value="The date range that this organization **should** be considered available." />

Again maybe wrong use of "should" in `./valuesets/ValueSet-UKCore-OperationOutcomeIssueDetails.xml`

./valuesets/ValueSet-UKCore-OperationOutcomeIssueDetails.xml:280:                       <display value="Number of items on a prescription **should** be between 1 and 4"/>
./valuesets/ValueSet-UKCore-OperationOutcomeIssueDetails.xml:382:                       <display value="Repeat count **should** be between 1 and 99"/>

**Comment by ryma2fhir** [comment]
Thanks for the response. I have carried out the changes.

**Review by declankieran-nhsd — APPROVED** [review]

**Pull request merged**
