### PR TITLE
Updated descriptions to match IG.

### PR DESCRIPTION
**Pull request by declankieran-nhsd**
Updated descriptions to match IG.

### CODE REVIEW

**Comment by ryma2fhir** [comment]
Does the version number and date need updating on these?

**Review by ryma2fhir — APPROVED** [review]

**Comment by APageNHS** [comment]
I would suggest merging latest develop changes in - potentially my MedicationCode changes will cause conflicts

**Comment by declankieran-nhsd** [comment]
@APageNHS I was actually thinking of waiting until you had merged into develop and it was fixed, your change should hopefully have develop back in proper order.  Then I was going to merge develop into my branch, make sure there are no errors introduced from my branch, before this looking to merge into develop

**Comment by declankieran-nhsd** [comment]
@APageNHS Sorry, I see you've already merged into develop, thought you were saying to merge this in first!

**Pull request merged**
