### PR TITLE
updated with 0.5.0 profiles

### PR DESCRIPTION
**Pull request by ryma2fhir**
updated capability statement ready for UKCore STU2 IG

### CODE REVIEW

**Review by johngeo — APPROVED** [review]
Looks fine to me.

**Comment by ryma2fhir** [comment]
QuestionaireResponse example: error on question "Do you have allergies?" changed Questionaire example from boolean to string to allow the response "I am allergic to amoxicillin."

**Comment by ryma2fhir** [comment]
Two errors:

> [examples/UKCore-Bundle-AllergyList-Example.xml](https://github.com/NHSDigital/FHIR-R4-UKCORE-STAGING-MAIN/blob/fix/STU2_updateCapabilityStatement/examples/UKCore-Bundle-AllergyList-Example.xml)
> 
>     ❌ Check profiles are not present in resource (Implementation Guide Best Practice)
> 
>     Error: expect(received).toBeTruthy()
> 
>     Received: false

Not sure what this means but I get no errors when validating in swagger


> [examples/UKCore-Medication-Sn-TransferDegradMedEntry-Example.xml](https://github.com/NHSDigital/FHIR-R4-UKCORE-STAGING-MAIN/blob/fix/STU2_updateCapabilityStatement/examples/UKCore-Medication-Sn-TransferDegradMedEntry-Example.xml)
> 
>     ❌ FHIR Validation - UKCore
> 
>     Error: expect(received).toBeFalsy()
> 
>     Received: "WARNING None of the codings provided are in the value set 'UK Core Medication Code' (https://fhir.hl7.org.uk/ValueSet/UKCore-MedicationCode), and a coding should come from this value set unless it has no suitable code (note that the validator cannot judge what is suitable) (codes = http://snomed.info/sct#196421000000109) [ Location - Medication.code] [ Location - Line 1, Col 199]"

Can ignore as we expect coding not to be in value set

**Comment by KevinMayfield** [comment]
First error 

Remove all meta.profiles from all the list entries

<meta>
  <profile value="https://fhir.hl7.org.uk/StructureDefinition/UKCore-List"/>
</meta>

**Comment by KevinMayfield** [comment]
Second error is because the example is referring to SNOMED codesystem and not dm+d

**Comment by KevinMayfield** [comment]
Also 2nd issue is logged against UKCore

https://simplifier.net/hl7fhirukcorer4/ukcore-medicationcode/~issues/2452

**Comment by ryma2fhir** [comment]
removed

**Pull request merged**
